services:
  # Database Service
  db:
    image: mysql:8.0
    container_name: neurasky_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: neurasky_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Backend Service (Django)
  backend:
    build: ./backend_neurasky
    container_name: neurasky_backend
    image: ${BACKEND_IMAGE_NAME}
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./backend_neurasky/.env  # Uses your existing .env file
    environment:
      # Overriding DB connection to use the docker service name 'db'
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=neurasky_db
      - DB_USER=root
      - DB_PASSWORD=9999
    volumes:
      - ./backend_neurasky:/app  # Hot-reloading for development

  # Frontend Service (Next.js)
  frontend:
    build: ./frontend_neurasky
    container_name: neurasky_frontend
    image: ${FRONTEND_IMAGE_NAME}
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      # Tell Next.js where the API is located
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend_neurasky:/app
      - /app/node_modules
      - /app/.next

volumes:
  db_data: